# Imagen base ligera de Python
FROM python:3.10-slim

# Instala Java 11 (necesario para Spark)
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean

# Establece la variable de entorno JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

# Instala Poetry
RUN pip install poetry

# Copia los archivos de configuración de Poetry primero (mejora el cacheo de dependencias)
COPY pyproject.toml poetry.lock* /app/

WORKDIR /app

# Instala las dependencias del proyecto (sin instalar el propio paquete aún)
RUN poetry install --no-root

# Copia el resto del código del proyecto
COPY . /app

# Puerto por defecto para MLflow UI y Streamlit
EXPOSE 5000
EXPOSE 8501

# Comando por defecto (puedes cambiarlo según lo que quieras lanzar)
CMD ["poetry", "run", "python", "src/main.py"]